PRODUCT_SHEETS = ["猫人", "欧迪芬", "草本初色", "三枪-恒源祥-南极人男内裤", "抖音代发"]

DATA_SHEETS = [
    "主仓",
    "欧迪芬库存",
    "猫人儿童京东",
    "猫人唯品会",
    "猫人自营",
    "猫人pop",
    "三枪拼多多",
    "三枪自营",
    "三枪唯品",
    "恒源祥唯品会",
    "恒源祥自营",
    "恒源祥拼多多",
    "joae自营",
    "欧迪芬自营",
    "欧迪芬唯品",
    "草本初色唯品1",
    "草本初色唯品2（陆）",
    "草本初色自营",
    "南极人自营",
    "浪莎童装自营",
    "浪莎童装唯品",
    "包装.工厂库存",
]

SHEET_BRAND = {
    "主仓": "全部",
    "欧迪芬库存": "欧迪芬",
    "猫人儿童京东": "猫人",
    "猫人唯品会": "猫人",
    "猫人自营": "猫人",
    "猫人pop": "猫人",
    "三枪拼多多": "三枪",
    "三枪自营": "三枪",
    "三枪唯品": "三枪",
    "恒源祥唯品会": "恒源祥",
    "恒源祥自营": "恒源祥",
    "恒源祥拼多多": "恒源祥",
    "joae自营": "joae",
    "欧迪芬自营": "欧迪芬",
    "欧迪芬唯品": "欧迪芬",
    "草本初色唯品1": "草本初色",
    "草本初色唯品2（陆）": "草本初色",
    "草本初色自营": "草本初色",
    "南极人自营": "南极人",
    "浪莎童装自营": "浪莎童装",
    "浪莎童装唯品": "浪莎童装",
    "包装.工厂库存": "包装工厂",
}

JOAE_COLUMNS = {
    "key": ["条形码"],
    "inventory": ["库存"],
    "yesterday": ["今日销量（已出库+未出库）"],
    "seven": ["7日销量（已出库）"],
    "thirty": ["30日销量（已出库）"],
}

DATA_COLUMNS = {
    "主仓": {
        "key": ["商品编码"],
        "inventory": ["实际可用数"],
        "yesterday": ["昨日销量"],
        "seven": ["7天销量"],
        "thirty": ["月销量"],
    },
    "欧迪芬库存": {
        "key": ["商品编码"],
        "inventory": ["可用数"],
        "yesterday": [],
        "seven": [],
        "thirty": [],
    },
    "猫人儿童京东": {
        "key": ["条码"],
        "inventory": ["现货库存"],
        "yesterday": ["昨日总销售量"],
        "seven": ["7日总销售量"],
        "thirty": ["30日总销售"],
    },
    "猫人唯品会": {
        "key": ["主条码"],
        "inventory": [],
        "yesterday": ["昨天销量"],
        "seven": ["7天销量"],
        "thirty": ["30天销量"],
    },
    "猫人自营": {
        "key": ["条码"],
        "inventory": ["现货库存"],
        "yesterday": ["昨日总销售量"],
        "seven": ["7日总销售量"],
        "thirty": ["30日总销售"],
    },
    "猫人pop": {
        "key": ["条形码"],
        "inventory": [],
        "yesterday": ["昨日销量"],
        "seven": ["7日销量"],
        "thirty": ["30日销量"],
    },
    "三枪拼多多": {
        "key": ["条形码【商品编码】"],
        "inventory": [],
        "yesterday": ["昨日"],
        "seven": ["近7天"],
        "thirty": ["近30天"],
    },
    "三枪自营": {
        "key": ["条形码"],
        "inventory": ["库存"],
        "yesterday": ["昨日出库件数"],
        "seven": ["7天出库件数"],
        "thirty": ["30天出库件数"],
    },
    "三枪唯品": {
        "key": ["系统条码"],
        "inventory": [],
        "yesterday": ["求和项:昨日销量"],
        "seven": ["求和项:近七天销量"],
        "thirty": ["求和项:近30天销量"],
    },
    "恒源祥唯品会": {
        "key": ["主条码"],
        "inventory": [],
        "yesterday": ["昨日销量"],
        "seven": ["7天销量"],
        "thirty": ["30天销量"],
    },
    "恒源祥自营": {
        "key": ["条码"],
        "inventory": ["库存"],
        "yesterday": ["昨日销量"],
        "seven": ["近7天销量"],
        "thirty": ["30天销量"],
    },
    "恒源祥拼多多": {
        "key": ["条形码【商品编码】"],
        "inventory": [],
        "yesterday": ["昨日"],
        "seven": ["近7天"],
        "thirty": ["近30天"],
    },
    "joae自营": JOAE_COLUMNS,
    "欧迪芬自营": JOAE_COLUMNS,
    "欧迪芬唯品": {
        "key": ["系统条码"],
        "inventory": ["云仓库存"],
        "yesterday": ["昨日销量"],
        "seven": ["7天销量"],
        "thirty": ["30天销量"],
    },
    "草本初色唯品1": {
        "key": ["系统条码"],
        "inventory": ["云仓存库"],
        "yesterday": ["昨日日销量"],
        "seven": ["7天"],
        "thirty": ["近30天"],
    },
    "草本初色唯品2（陆）": {
        "key": ["系统条码"],
        "inventory": ["合肥库存"],
        "yesterday": ["昨日销量"],
        "seven": ["近7天销量"],
        "thirty": ["近30天销量"],
    },
    "草本初色自营": JOAE_COLUMNS,
    "南极人自营": JOAE_COLUMNS,
    "浪莎童装自营": {
        "key": ["条形码"],
        "inventory": ["库存"],
        "yesterday": ["8.2"],
        "seven": ["近7天销量"],
        "thirty": ["近30天销量"],
    },
    "浪莎童装唯品": {
        "key": ["系统条码"],
        "inventory": ["聚水潭库存"],
        "yesterday": ["8.20销量"],
        "seven": ["7天销量"],
        "thirty": ["30天销量"],
    },
    "包装.工厂库存": {
        "key": ["货号"],
        "inventory": ["数量"],
        "yesterday": [],
        "seven": [],
        "thirty": [],
    },
}

REPEATED_INVENTORY_HEADERS = {"合肥库存", "库存", "合计库存"}

NEW_CHANNEL_SCHEMAS = {
    "猫人自营": {
        "keywords": ["猫人", "自营"],
        "sheets": [
            {
                "sheet": "2026年8月",
                "key": ["条码"],
                "inventory": ["现货库存"],
                "in_transit": ["在途"],
                "yesterday": ["昨日总销售量"],
                "seven": ["7日总销售量"],
                "thirty": ["30日总销售"],
            }
        ],
    },
    "猫人唯品会": {
        "keywords": ["猫人", "唯品"],
        "sheets": [
            {
                "sheet": "Sheet1",
                "key": ["主条码"],
                "inventory": [],
                "in_transit": [],
                "yesterday": ["昨天销量"],
                "seven": ["7天销量"],
                "thirty": ["30天销量"],
            },
            {
                "sheet": "1",
                "key": ["条码"],
                "inventory": ["在售库存"],
                "in_transit": [],
                "yesterday": [],
                "seven": [],
                "thirty": [],
            },
        ],
    },
}

PRODUCT_FIELDS = {
    "barcode": ["条形码"],
    "product_code": ["产品编号"],
    "jd_code": ["京东条码", "京东/唯品条码"],
    "name": ["产品名称"],
    "spec": ["产品规格"],
    "color": ["颜色"],
    "category": ["品类"],
    "supplier": ["供应商"],
    "sale_price": ["京东售卖价格", "唯品售卖价格", "售卖价"],
    "purchase_price": ["采购价"],
    "grade": ["等级"],
    "status": ["商品情况"],
    "packaging": ["包装"],
    "material": ["面料成分"],
    "notes": ["链接备注"],
}
